### PR TITLE
Hack: rename webp images to jpeg

### LINKED ISSUE #1414: Images are being downloaded as .webp instead of .jpg
**Describe the bug**
Images are being downloaded as `.webp` files instead of the usual `.jpg` files.

**To Reproduce**
I'm using the Python module.
`L = instaloader.Instaloader(download_geotags=False, compress_json=False, filename_pattern='{mediaid}')`
I first saved thousands of shortcodes from a particular hashtag by iterating through:
```
post_iterator = instaloader.NodeIterator(
    L.context, "9b498c08113f1e09617a1703c22b2f32",
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
    lambda n: instaloader.Post(L.context, n),
    {'tag_name': hashtagname},
    f"https://www.instagram.com/explore/tags/{hashtagname}/"
)
```
Then I downloaded the post using:
```
post = instaloader.Post.from_shortcode(L.context, 'shortcode')
L.download_post(post, target='target')

```
This is one of the posts that saved as `.webp`:
`'CZbzQ5vL0tB'`

**Expected behavior**
Save the image as a `.jpg` instead of `.webp`

**Error messages and tracebacks**
N/A

**Instaloader version**
4.8.4

**Additional context**
I had not tried scraping posts since about two weeks ago so it seems like this is something new. I'm only getting `.webp` files for posts from this year (although not all). I downloaded 417 posts from this month (February) and the image files I got were 638 jpgs and 106 webps.
I'm not expecting this to be fixed if this is considered an non-issue but I thought I should bring it up

### PR DESCRIPTION
**Pull request by miriq**
Fixes #1414

For some reason Instagram incorrectly sets the file extension to webp, even though the image is a jpg. This pull request assumes that webp images are always jpgs, that is verified using the magic header bytes "ffd8ff". If for some reason the header bytes do not match, it will print an error and exit.

### CODE REVIEW

**Comment by afterdelight** [comment]
so if it was a real webp it will reject the webps to be downlaoded?

**Comment by miriq** [comment]
In that case it will download the webp but save it as jpg, and print an error. This way was easier to implement: assume that instagram always returns jpeg, and if in the future that's not true then hopefully somebody can fix it. Or maybe even remove this hack, because it looks like a bug on instragram's side.

**Comment by afterdelight** [comment]
OK

**Comment by aandergr** [comment]
Hi! Thanks for your effort and for sharing your ideas on how to fix this. I prefer the approach outlined in #1447 to use the Content-Type header to determine an appropriate file extension.

**Comment by miriq** [comment]
Ok no worries, I had been using this workaround for a few days and I opened this pull request because nobody else had a fix, now that it is properly fixed this hack is not needed anymore.

**Pull request closed without merging**
