### PR TITLE
Added `is_reposted`, `original_poster_profile` in `StoryItem`

### PR DESCRIPTION
**Pull request by StamKaly**
A lot of times the "owner" is reposting a story he was tagged into. I am calling the person who tagged the "owner" as "original_poster".

The GraphQL query from such a reposted story has information inside the `tappable_objects` key of each `StoryItem`.
For example for a reposted story it looks like this:

```
"tappable_objects": [
                        {
                            "__typename": "GraphTappableMention",
                            "x": 0.49967163378806606,
                            "y": 0.5150924938267181,
                            "width": 0.9216036185381431,
                            "height": 0.9216036185381431,
                            "rotation": 0.0,
                            "custom_title": null,
                            "attribution": null,
                            "username": "username",
                            "full_name": "User Name",
                            "is_private": false
                        }
                    ]
```

And for a story that was NOT reposted there is nothing inside `tappable_objects` with the `__typename` of `GraphTappableMention`.

The functions I added are pretty self explanatory and I followed the structure the rest of the project has.

### CODE REVIEW

**Comment by StamKaly** [comment]
Resolves #1146

**Comment by StamKaly** [comment]
It seems like this creates a loop because `GraphTappableMention` also appears with the `owner`'s information on the `original_poster`'s story. So it would flag the "original story" also as reposted.

Looking for a workaround..

**Comment by aandergr** [comment]
Just by the logic of the code, `is_reposted` does not make a lot of sense, since it is equivalent to `original_poster_profile is not None`.

Hence, I would prefer a function that returns all tappable mention profiles.

**Comment by StamKaly** [comment]
That's true, I'll rewrite that function.

**Pull request closed without merging**
