### PR TITLE
Update code formatting to be cleaner and closer to 3.6+ standards.

### PR DESCRIPTION
**Pull request by MiguelX413**
Replacing https://github.com/instaloader/instaloader/pull/1507

This pull request aims to update the writing of the code by updating string formatting to f-strings, removing u-strings, removing unnecessary parentheses, and updating the way in which variables are typed.
These commits were made in consideration of Python 3.6 and newer, as that is the oldest version advertised by the project.

### CODE REVIEW

**Comment by aandergr** [comment]
Thanks for going through the code and changing it in order to make it cleaner and better comprehensible!

Please leave out `docs/sphinx_autodoc_typehints.py`, as this file is copied from another project and changing it makes it harder to keep it up to date with upstream when necessary.

I noticed that despite your changes, several strings are still built with `.format()`. Is there a rationale behind when to use f-strings and when to use `.format()`?

**Comment by MiguelX413** [comment]
> Thanks for going through the code and changing it in order to make it cleaner and better comprehensible!
> 
> Please leave out `docs/sphinx_autodoc_typehints.py`, as this file is copied from another project and changing it makes it harder to keep it up to date with upstream when necessary.

Got it!

> 
> I noticed that despite your changes, several strings are still built with `.format()`. Is there a rationale behind when to use f-strings and when to use `.format()`?

I felt that in cases like https://github.com/instaloader/instaloader/blob/e4ba49c2be429780a7a371046d3376e6cee5de65/instaloader/__main__.py#L23-L28 or when methods are being used within, it would probably decrease readability more to change some strings to f-strings.

**Comment by MiguelX413** [comment]
Also, I would like to propose that https://github.com/psf/black be used for this project.

**Comment by MiguelX413** [comment]
I would also like to reformat the namedtuples to use Typing NamedTuple in the new class format
But I'm not entirely sure what the types of the attributes should be

**Comment by aandergr** [comment]
I have also thought about Black, and find it practical in principle to automate the formatting of the code by a software. But the problem is that we can't introduce such a change, because it makes it very difficult for downstream users who use a modified Instaloader version to merge our updates and merge them with their modifications. Unfortunately, the same is true for reformatting the strings, as the code is changed in very many places.

**Comment by MiguelX413** [comment]
> I have also thought about Black, and find it practical in principle to automate the formatting of the code by a software. But the problem is that we can't introduce such a change, because it makes it very difficult for downstream users who use a modified Instaloader version to merge our updates and merge them with their modifications. Unfortunately, the same is true for reformatting the strings, as the code is changed in very many places.

Do you mean the change to f-strings etc too?

**Comment by MiguelX413** [comment]
Do you mind PostComment being made a subclass of PostCommentAnswer in https://github.com/instaloader/instaloader/commit/6ceac282553d738bf7509dcc71c894b46813adb3?
Also, do you have any idea why the docs wont build for it? @aandergr

**Comment by MiguelX413** [comment]
What do you think of the types in https://github.com/instaloader/instaloader/commit/943666b48f4d2446e1120863eb78c55d81de250b? @aandergr

**Comment by MiguelX413** [comment]
Why is namedtuple a func instead of class in the docs btw?

**Comment by MiguelX413** [comment]
What do you think of the types in https://github.com/instaloader/instaloader/commit/0c08405e5a71fbf8125233e5652fff30ccf93d00? @aandergr

**Comment by MiguelX413** [comment]
Do you think we could incorporate any of the changes in this PR on their own if not all of them? @aandergr

**Comment by MiguelX413** [comment]
I moved a few things into #1610.

**Pull request closed without merging**
