### PR TITLE
Random sleep

### PR DESCRIPTION
**Pull request by tari3x**
The current download speed seems too agressive: https://github.com/instaloader/instaloader/issues/2172. 

This change slows it down such that I'm able to download thousands of posts before getting banned.

### CODE REVIEW

**Comment by GabeMillikan** [comment]
[This](https://github.com/instaloader/instaloader/blob/5509ea7daf7f5e81534d4eb996c8afd478704426/instaloader/instaloadercontext.py#L345-L348l) is the appropriate location to adjust the sleeping logic.

**Comment by tari3x** [comment]
I feel like I tried and it didn't work the expected way - wasn't granular enough. Can you remind me the difference between InstaloaderContext.do_sleep and RateController.sleep?

**Comment by sapphirepro** [comment]
Yes, please accept this merge. Default included "sleep" is useless and not working causing fast downloads and fast ban

**Comment by sapphirepro** [comment]
But also, maybe could add some timings between photos too, not only posts? Cause grabbing all 10 post photos instantly if obvious robot mode, human can not manually look instantly whole 10 photos with no time basically. So that between photos random between 1-5 secs and some 5-15 between posts. Then +/- human like

**Comment by aandergr** [comment]
Does not make any sense. Apart from the many unrelated changes, this essentially destroys the rate controller by not waiting the determined interval, but rather a randomly determined, often shorter!, interval.

**Comment by tari3x** [comment]
The problem with the current rate controller is that it does not work - it gets you banned pretty quickly. As with the other change, I am offering you a piece of code that does work pretty reliably. But since it doesn't make sense to you, I guess there's not much hope.

**Comment by cyberjock** [comment]
I second this.  I'm trying to help a friend retrieve a copy of one of his family member's instagram page, and he keeps getting banned for too many requests.  Can't even get 100 pictures downloaded before instagram catches on.  Being that there's over 20k images, instaloader will not work for this job.  Even waiting 30 seconds between steps would be fine as we're not time limited.

(His family member passed away that owns the account) and his family asked him to try to retrieve all of the pictures)

**Pull request closed without merging**
