### PR TITLE
Add meth:get_tagged_posts to Profile

### PR DESCRIPTION
**Pull request by e5150**
Initial support for getting posts where a user has been tagged, which was recently added to the official website. (Suggested in #73.) 
Not sure how to best incorporate into the CLI, prepending "@" to the username would seem intuitive as a target, but that's taken. Maybe `--tagged` and `--tagged-only` like what is done for stories. And I don't know what default dirname makes the most sense, `tagged-user`, `post-owner` or possibly `@tagged-user`. With `@tagged-user` there will at least not be conflicts if one wants to `--fast-update --tagged-only username` and some post has been downloaded from `:feed` or such.

### CODE REVIEW

**Comment by Thammus** [comment]
Thank you for your code! We merged it.

**Comment by e5150** [comment]
Actually, there is an issue with my code, `self` is passed as third argument to the `Post` constructor, which is inaccurate for posts where the owner is not the tagged user themself. This ought to be `self if int(node['owner']['id']) == self.userid else None`, sorry.

**Comment by aandergr** [comment]
> Fix owner_profile for Profile.get_tagged_posts()

Thanks! I pushed it to our repository as b5aa268.

> Not sure how to best incorporate into the CLI

Not sure, either. Maybe `USER:tagged` as target name. So we could check whether target.endswith(':tagged'); and Instaloader already does colons in dirnames (e.g. target `:saved`). A `--tagged`/`--tagged-only` flag would be an option, too, but if it downloads them with target `USER` the file's path would not indicate whether it was posted by the user or the user only has been tagged in. I tend to be against `@tagged-user` or similar, because target.startswith('@') is already taken for followees and I'm unsure whether we'd run into problems with Windows again when having `@` in path names.

Maybe we could go with `USER:tagged` as target name and add flags `--tagged`/`--tagged-only` that add/substitute each `USER` target with `USER:tagged`?

**Comment by e5150** [comment]
[`700b3a8`](https://github.com/instaloader/instaloader/pull/154/commits/700b3a8d094f552caa638a9d91f9221392a8e3f0) adds support for `--tagged`/`--tagged-only`, which is passed along to `download_profile()` rather than manipulating the target list. I wanted to go via `download_profile` to not have duplicate code for the checks for id, private, blocked and such. Support for `USER:tagged` could easily be added to imply `download_tagged_only` for that profile.

**Comment by aandergr** [comment]
Great, thanks! Also thanks for already having it merged with my recent change to `__main__.py`. The help texts for the flags should be copied into `docs/cli-options.rst`, but I can also do that (actually I feel it's my fault to still haven't found a proper solution for that).

I'm going to push these commits into our `v4.1-dev` branch which I'll soon start, since it touches existing code without fixing bugs.

**Comment by aandergr** [comment]
Thanks, it's in `v4.1-dev` now. I squashed it together with the merge commits into one commit to linearize the tree, I hope that's okay.

**Comment by aandergr** [comment]
I changed the tagged target from `user:tagged` to `user/:tagged`. Since `user:tagged` is not supported as a target specification for the CLI, one couldn't invoke Instaloader with `instaloader [flags] */` when there were `ùser:tagged` directories present. I hope this solution is ok.

**Pull request closed without merging**
