### PR TITLE
download-limit arg added to limit the downloads

### PR DESCRIPTION
**Pull request by Hassibayub**
Motivation:
The count arg should limit the downloads, but it is not working as intended, it was something I needed in my project, and I once saw people talking about this problem which is still not resolved.

Solution:
I added a new arg "-dl, --download-limit" to limit the download. 

>Documentation is not yet updated, I want to you to check and approve the changes first.

### CODE REVIEW

**Comment by Hassibayub** [comment]
Please write feedback. I am looking forward to it.

**Comment by ekalin** [comment]
Wouldn't it make more sense to fix `--count` than to add another option that does the same thing?

**Comment by Hassibayub** [comment]
The --count doesn't work.

**Comment by afterdelight** [comment]
what does this command do?

**Comment by Hassibayub** [comment]
You can specify the number of downloads, i.e., if you want to download 10 contents (video, pictures, stories), you can specify  `--download-limit 10`, and the app will stop after 10 downloads.

While in `--count 10`, I don't see the app stop after 10 downloads

**Comment by MustafaBaypara** [comment]
how can i use this version?

**Comment by MustafaBaypara** [comment]
how can i use on python ?

**Comment by Hassibayub** [comment]
> how can i use on python ?

`python instaloader.py <you args> --download-limit 10` to limit downloads to 10 only.

**Comment by MustafaBaypara** [comment]
> > how can i use on python ?
> 
> `python instaloader.py <you args> --download-limit 10` to limit downloads to 10 only.

limits not working on python, when i try on terminal it is work

**Comment by aandergr** [comment]
> Motivation: The count arg should limit the downloads, but it is not working as intended,

The `--count` argument applies to #hashtag, %location_id, :feed, and :saved, as described in the documentation. It is working as intended.

> Solution: I added a new arg "-dl, --download-limit" to limit the download.

It is quite trivial for the user to only download a certain count of posts of a profile, e.g. by calling download_post() for each post of an islice()'d profile.get_posts(). There is no need to include that in the CLI.

**Comment by afterdelight** [comment]
> > how can i use on python ?
> 
> `python instaloader.py <you args> --download-limit 10` to limit downloads to 10 only.

ok, thank you. this PR is very useful for me since instagram randomly lock accounts when downloading many medias.

**Comment by MustafaBaypara** [comment]
@Hassibayub hey what happened to "-dl"

**Comment by MustafaBaypara** [comment]
ok i get back with ur pull requests ty

**Comment by dagolinuxoid** [comment]
> Motivation: The count arg should limit the downloads, but it is not working as intended, it was something I needed in my project, and I once saw people talking about this problem which is still not resolved.
> 
> Solution: I added a new arg "-dl, --download-limit" to limit the download.
> 
> > Documentation is not yet updated, I want to you to check and approve the changes first.

Actually it's a good idea. I was looking for the option as well. Honestly it would be better to have the option included into instaloader.

**Pull request closed without merging**
