### PR TITLE
Workaround for empty posts

### LINKED ISSUE #2319: Cannot retrieving posts from profile
**Describe the bug**

Cannot retrieving posts from profile when logging in
When I delete --login, retrieving posts from profile only gets the last 4 posts and --fast-update is not working
When I delete --login and --fast-update, retrieving posts from profile stops at 12 posts, responses a 401 error (Please wait a few minutes before you try again.)

**To Reproduce**

instaloader --max-connection-attempts=1 **--login=myaccount** --stories --no-metadata-json --abort-on=302,400,429,401 username --fast-update
instaloader --max-connection-attempts=1 --stories --no-metadata-json --abort-on=302,400,429,401 username --fast-update

**Expected behavior**

retrieve all the posts from profile and download them successfully

**Error messages and tracebacks**

with --login:
Loaded session from C:\Users\XXXXXXX\AppData\Local\Instaloader\session-myaccount.
Logged in as myaccount.
[1/1] Downloading profile username
username\2024-06-03_15-56-51_UTC_profile_pic.jpg already exists
Retrieving posts from profile username.
Downloading stories
[1/1] Retrieving stories from profile username.
[  1/  2] username\2024-07-30_10-11-45_UTC.mp4 exists username\2024-07-30_10-11-45_UTC.jpg exists
Saved session to C:\Users\XXXXXXX\AppData\Local\Instaloader\session-myaccount.

without --login:
--login=USERNAME required to download stories.
Hint: Use --login to download higher-quality versions of pictures.
[1/1] Downloading profile username
username\2024-06-03_15-56-51_UTC_profile_pic.jpg already exists
Retrieving posts from profile username.
[ 1/14] username\2024-07-30_08-41-43_UTC.jpg exists [XXXXXXXXX…] unchanged
[ 2/14] username\2024-07-27_11-43-53_UTC.jpg exists [XXXXXXXXX…] unchanged
[ 3/14] username\2024-07-25_08-17-28_UTC.jpg exists [XXXXXXXXX…] unchanged
[ 4/14] username\2024-07-10_08-26-49_UTC.jpg exists [XXXXXXXXX…] unchanged

**Instaloader version**

4.12.1 (also test in 4.10.2 , and it shows the same problem)

### PR DESCRIPTION
**Pull request by Caramel7**
Fixes #2319

Possible workaround for Instagram returning empty posts list.
Seems to work, but not sure about any side effects.

### CODE REVIEW

**Comment by sapphirepro** [comment]
Did work for me

**Comment by kmastra** [comment]
yeah can confirm it works right now! thanks!

**Comment by Luan1Schons** [comment]
Working here with get_posts, no side effects

**Comment by Sevrima** [comment]
works fine for me too

**Comment by Montana** [comment]
Worked.

**Comment by Superkaizhen07** [comment]
work with no login ?

**Comment by J3-strip** [comment]
> Fixes #2319
> 
> Possible workaround for Instagram returning empty posts list. Seems to work, but not sure about any side effects.

Worked great, if not better than before! Thanks.

restored my files I adjusted on previous thread, updated with your work around and it’s currently flawless.


Thanks!

**Pull request merged**
