### PR TITLE
download all posts for a given location

### PR DESCRIPTION
**Pull request by tari3x**
This resolves https://github.com/instaloader/instaloader/issues/2159.

### CODE REVIEW

**Comment by tari3x** [comment]
Update: the change to ignore has_next_page seems necessary for locations, but does break for downloading profiles, so I guess you need an extra argument to the iterator.

**Comment by aandergr** [comment]
We cannot merge a pull request that breaks downloading profiles.

Why does the if condition need to be removed for locations?

**Comment by tari3x** [comment]
See the comment I left in the code: "This value seems to be a lie, at least for some location feeds.". So the feed says there's no next page, even though there are more posts, and it will give them to you if you ask explicitly.

**Comment by tari3x** [comment]
As with the other pull request, this is a sketch that demonstrates the idea, and I'm hoping you'd be ok to apply the polish as you see fit.

**Comment by aandergr** [comment]
Pull requests are the way to incorporate bug fixes or general improvements, also in the form of new features, into Instaloader. Before we can merge one, however, it must meet certain requirements in terms of usefulness and quality of implementation, only then does it make sense for the project to adopt the code. We are happy to offer support, but we simply cannot merge pull requests that disrupt existing functionality.

**Comment by tari3x** [comment]
I am sorry to hear that you misunderstood what I said and opted to reject my contribution towards this functionality to instaloader. The multiple isssues that reference this will remain unresolved.

**Pull request closed without merging**
