### PR TITLE
Handle StoryImage & StoryVideo in `download_post`

### PR DESCRIPTION
**Pull request by fireattack**
Instaloader supports to download single post which works with Stories. But the returned data is slightly different and can't be properly handled by existing Post class. I patched this part as well.

They are called typename = StoryImage and StoryVideo (NOT GraphStoryImage or GraphStoryVideo returned from the Stories timeline as StoryItem.)

Also note: weirdly, the StoryVideo returned by single post API doesn't behave like GraphStoryVideo returned by Stories timeline either. It has no self._node['video_url'] or self._node['video_resources']. So you can only get the video from self._iphone_struct['video_versions'].

### CODE REVIEW

**Comment by aandergr** [comment]
That's a nice finding - cool to see that it just works!

`Post` seems to already well handle nodes with type `StoryImage`. In the case of a `StoryVideo`, it fails when accessing the properties `video_view_count` and `video_duration`. I think it would be okay to just let it return `None` in this case. Also, `Post.supported_graphql_types()` should then also list `StoryImage` and `StoryVideo` :)

I also tried to put the node returned by that query into `StoryItem`, but that class could not access the fields video_url or expiring_at_timestamp. Seems that `Post` is a better fit.

It could be that StoryItem is actually redundant and all its functionality would be covered by Post with only a few changes.

**Comment by aandergr** [comment]
One problem I noticed here is that the properties `video_view_count` and `video_duration` fail when the Post had been initialized with a StoryVideo, so actually we do not have full compatibility yet.

Also, but this is more a long-term issue: I am not yet sure what a good strategy might be here, since the Post and StoryItem structures may require some refactoring in the near future. I don't like the redundancy that we have now, and also, at least Post needs some work to properly support the new 'sections' format outlined in #1240, needed to fix #1080 and #1129.

**Comment by fireattack** [comment]
Good to know! I will leave this one open for now as we think about how to refactor the structure for the long term.

**Comment by fireattack** [comment]
@aandergr:

Despite the fact this is just a quick workaround instead of full proper implementation/refactoring around `StoryImage` can we merge this in the meantime? 

Currently, downloading a single story with static image (`StoryImage`) straight up does not work (as no image would be downloaded):

```py
import instaloader

my_username = 'yourusername'

L = instaloader.Instaloader()
L.load_session_from_file(my_username)

media_id = 2793728037449719617 # replace with any story that has a static image (no special effect etc.)
shortcode = instaloader.Post.mediaid_to_shortcode(media_id)
```

```
Loaded session from C:\Users\****\AppData\Local\Instaloader\session-****.
Warning: <Post CbFUNknPV9B> has unknown typename: StoryImage
[そういえば新しい トイカメラ買いました 楽しい！] json
```

(It only downloads .json.xz and .txt, not the image.)

**Comment by aandergr** [comment]
I think in its current form (i.e. Post and StoryItem being separate classes), Post is not supposed to handle StoryItems, even though the class seems to work mostly fine with them. I would rather favor to have a method `from_mediaid()` in StoryItem that fetches the StoryItem with the given mediaid, as e.g.

```python
    @classmethod
    def from_mediaid(cls, context: InstaloaderContext, mediaid: int):
        """Create a StoryItem object from a given mediaid"""
        pic_json = context.graphql_query(
            '2b0673e0dc4580674a88d426fe00ea90',
            {'shortcode': Post.mediaid_to_shortcode(mediaid)}
        )
        shortcode_media = pic_json['data']['shortcode_media']
        if shortcode_media is None:
            raise BadResponseException("Fetching StoryItem metadata failed.")
        return cls(context, shortcode_media)
```

**Comment by fireattack** [comment]
Thanks!

**Pull request closed without merging**
